#!/usr/bin/env python3
"""Rotate a DFA ADW schema password and update its OCI Vault connection secret.

Example:
    PYTHONPATH=src python scripts/rotate_adw_database_password.py

Defaults: ``DFA_USER``, ``ADMIN``, ``config.ini.mine``, and the ``TEST``
configuration section. All can be overridden with their corresponding option.

The script prompts only for the DBA password. It generates a secure target
password and never writes or prints it, then changes the database password and
creates a new CURRENT version of the existing consolidated connection secret.
"""

import argparse
import getpass
import os
import re
import secrets
import string
import sys
import tempfile
from pathlib import Path

import oracledb

from common.ocihelpers.vault import AdwSecrets
from dfa.bootstrap.envvars import bootstrap_local_machine_environment_variables

VALID_USERNAME = re.compile(r"^[A-Za-z][A-Za-z0-9_$#]{0,127}$")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--target-user", default="DFA_USER", help="Schema account whose password will be rotated (default: DFA_USER)."
    )
    parser.add_argument(
        "--admin-user", default="ADMIN", help="Database account with ALTER USER and DBA_USERS access (default: ADMIN)."
    )
    parser.add_argument(
        "--config-file", default="config.ini", help="DFA config.ini containing OCI and database connection settings."
    )
    parser.add_argument("--section", default="DFA", help="config.ini section (default: DFA).")
    parser.add_argument("--yes", action="store_true", help="Do not ask for the final destructive-action confirmation.")
    return parser.parse_args()


def validate_username(username, option):
    if not VALID_USERNAME.fullmatch(username):
        raise ValueError(f"{option} must be an unquoted Oracle username containing only letters, digits, _, $, or #")
    return username.upper()


def generate_password():
    """Match the password format generated by the DFA installer."""
    lowercase = string.ascii_lowercase
    return (
        "".join(secrets.choice(lowercase) for _ in range(6))
        + secrets.choice(string.ascii_uppercase)
        + "".join(secrets.choice(lowercase) for _ in range(6))
        + secrets.choice(string.digits)
    )


def connection_details():
    secrets = AdwSecrets()
    material = secrets.get_connection_material()
    dsn = (
        f'{os.environ["DFA_CONN_PROTOCOL"]}://'
        f'{os.environ["DFA_CONN_HOST"]}:{os.environ["DFA_CONN_PORT"]}/'
        f'{os.environ["DFA_CONN_SERVICE_NAME"]}'
    )
    return secrets, material, dsn


def main():
    args = parse_args()
    bootstrap_local_machine_environment_variables(args.config_file, args.section)

    target_user = validate_username(args.target_user, "--target-user")
    admin_user = validate_username(args.admin_user, "--admin-user")
    new_password = generate_password()
    admin_password = getpass.getpass(f"Password for {admin_user}: ")
    if not admin_password:
        raise ValueError("The administrator password cannot be empty")

    if not args.yes:
        answer = input(
            f"Rotate {target_user} and create a new CURRENT version of its configured OCI Vault secret? [y/N] "
        )
        if answer.lower() not in {"y", "yes"}:
            print("No changes made.")
            return

    secrets, material, dsn = connection_details()
    with tempfile.TemporaryDirectory(prefix="dfa_rotate_wallet_") as wallet_dir:
        wallet_path = Path(wallet_dir)
        wallet_path.chmod(0o700)
        (wallet_path / "cwallet.sso").write_bytes(material["wallet"])
        (wallet_path / "ewallet.pem").write_text(material["ewallet_pem"], encoding="utf-8")

        connection = oracledb.connect(
            user=admin_user,
            password=admin_password,
            dsn=dsn,
            wallet_password=material["wallet_password"],
            wallet_location=wallet_dir,
        )
        try:
            with connection.cursor() as cursor:
                cursor.execute(f'ALTER USER {target_user} IDENTIFIED BY "{new_password}"')
                cursor.execute(
                    "SELECT account_status, expiry_date FROM dba_users WHERE username = :username",
                    username=target_user,
                )
                status = cursor.fetchone()
        finally:
            connection.close()

    try:
        secrets.update_connection_password(new_password)
    except Exception as error:
        raise RuntimeError(
            "Database password changed, but the OCI Vault secret was not updated. "
            "Immediately use an approved recovery procedure to synchronize the database and secret."
        ) from error

    if status is None:
        print("Password rotated and Vault secret updated. DBA_USERS did not return the target user.")
    else:
        print(f"Password rotated and Vault secret updated. Account status: {status[0]}; expiry: {status[1]}")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"Rotation failed: {error}", file=sys.stderr)
        sys.exit(1)
